
# Step 1. Calculating all totoaba parameters for base case.

```{r load libraries}

library(here)
library(tidyverse)
library(kableExtra)

#devtools::install_github("james-thorson/FishLife")
library(FishLife)

```

```{r growth parameters}

# Totoaba macdonaldi is in FishLife database, so prediction for 'r' is informed by species-specific data.
Predict = Plot_taxa(Search_species(Genus="Totoaba",Species="macdonaldi")$match_taxonomy, mfrow=c(2,2))
knitr::kable(Predict[[1]]$Mean_pred, digits=3)
Predict[[1]]$Mean_pred %>%
  kbl() %>%
  kable_styling()

# Define the parameters for the biological resource
r <- 0.2012827 #from FishLife (above)
k <- 20226 #carrying capacity (biomass in mt) (source: INAPESCA 2020) 
sigma <- 0.0005526788 #catchability (source: INAPESCA 2020 via Andrew)

```


```{r calculating cost of poaching}

# W parameter, proportional increase in cost per unit (trip)
w_par <- read.csv(here("data","w_par.csv")) # Cost data, from Buche Bros

#Step one, get all annual operating costs
# Goal is to calculate cost per vessel trip (we have total fleet days per year which is number of vessels * fishing days per month)
# First calculate total annual costs for the entire fleet

w_par_ops <- w_par %>% 
  mutate(cost_crew_earnings = (totoaba_year * price_fishers_per_totoaba * monthly_earnings_paid)) %>% 
  mutate(cost_food_fuel = (foodfuel_day * total_fleet_days_year)) %>% 
  mutate(cost_gear = total_fleet_days_year*(gear_loss_day*gear_replacement)) %>% 
  mutate(revenue_per_month = (totoaba_year*(price_fishers_per_totoaba)) - (cost_crew_earnings-cost_food_fuel-cost_gear))

# Next, divide by total fishing days per year

w_par_val <- w_par_ops %>% 
  select(vessels, totoaba_day, total_fleet_days_year,cost_crew_earnings,cost_food_fuel,cost_gear,bribes_year,revenue_per_month) %>% 
  mutate(cost_per_trip = (cost_crew_earnings + cost_food_fuel + cost_gear + bribes_year)/total_fleet_days_year) 

#Adding in gear and vessel confiscation (calculated as a shared cost applied to the entire fleet)

w_pal_val_conf <- w_par_val %>%
  add_column(net_confs_cost_fleetday=664000/1920) %>% #Total cost as a proportion of reported confiscations averaged over the year (1,920 fishing trips total). 5,720 nets in the water each year (each vessel sets 2-3 nets), and 0.07 of those nets are confiscated (we know that there are 415 gear confiscation events each year). So if we assume that each net costs $1,600, then our total cost to the fleet is $664,000.
  add_column(vessel_confs_cost_fleetday=1230000/1920) %>% #Total cost as a proportion of reported vessel seizures averaged over the year (1,920 fishing trips total). There are 150 boats in total each year, and 0.546 are confiscated (there are 82 confiscations a year). So we assume each boat is worth $15,000, and therefore the total cost to the fleet is $1,230,000.
  add_column(fines_cost_fleetday=81675/1920) %>% #Total cost as a proportion of reported vessel seizures averaged over the year (1,920 fishing trips total). There are 11 arrests/convictions where people are fined $7,425/event, which would add an additional cost of $42.54.
  mutate(cost_per_trip = (cost_crew_earnings + cost_food_fuel + cost_gear + bribes_year)/total_fleet_days_year) %>% 
  mutate(cost_per_trip_wconf = cost_per_trip + net_confs_cost_fleetday + vessel_confs_cost_fleetday + fines_cost_fleetday)

# Final estimates of cost per trip (W)
W_low = 5051.262 #Low Season 
W_mid = 8385.344 # Mid Season
W_high = 14386.690 # High Season

```


```{r calculating cost of farming}

# Farming cost data, from Buche Bros
v_par <- read.csv(here("data","v_par.csv")) 

# Final estimate per tonne of totoaba:
v = 14896.55

# Calculating size at harvest
aqua_par_w <- read.csv(here("data","aqua_par_wild.csv"))
aqua_par_f <- read.csv(here("data","aqua_par_farm.csv"))

# At 4.5 years under farming conditions, a totoaba should have a 417 g swim bladder
# At 5 years under farming conditions, a totoaba should have a 530 g swim bladder

```

```{r conversion factor for buche}

#  Length-weight/age relationships from INAPESCA (2020), wild stock.
#  Weight in kg, length in cm.
dat_lw = read_csv(here("data", "andrew", "dat_inpesca_bio.csv"))

# Wet buche is 0.0161 of the total wet weight and up to 0.0300 in females (INAPESCA 2020) (wild-caught).
# Wet buche is 0.0135 of the fish body wet weight (Gonzalez-Felix et al. 2021) (aquaculture raised).

buche_ww <- dat_lw %>% 
  mutate(buche_g_low = (weight*0.0135)*1000) %>% #low is the Gonzalez-Felix et al. 2021 aquaculture-raised number.
  mutate(buche_g_av = (weight*0.0161)*1000) %>% #average reported by INAPESCA
  mutate(buche_g_max = (weight*0.0300)*1000) #large females reported by INAPESCA

ggplot() +
  theme_bw() +
  geom_ribbon(data = buche_ww, aes(x = years, ymin=buche_g_low, ymax=buche_g_max), fill = "grey70", alpha=0.5) +
  geom_line(data = buche_ww, aes(x = years, y = buche_g_av)) +
  xlab("Age of Totoaba") +
  ylab("Buche Mass (grams)") +
  geom_hline(yintercept=500, color="grey70", lty=2) #the average buche size reported by fishermen.

# Conversion factor is 0.019 (average of 0.0161, 0.0300, and 0.0135)

```