## Calculating Parameters for Totoaba Model ##

## All Values need to be in the units of totoaba tonnes ##

```{r load libraries}
library(here)
library(tidyverse)

```

```{r loading data}

dat_aqm <- read.csv(here("data","andrew","dat_aqm.csv")) #Aquaculture Mortality by Age (in Months)
dat_b <- read.csv(here("data","andrew","dat_b.csv")) #Biomass by Age (INAPESCA)
dat_bc <- read.csv(here("data","andrew","dat_bc.csv")) #Biomass, Number of Individuals by Year (INAPESCA) check?
dat_bio <- read.csv(here("data","andrew","dat_bio.csv")) #Biomass, Number of Individuals by Age (in Years) (INAPESCA)
dat_inapesca_bio <- read.csv(here("data","andrew","dat_inpesca_bio.csv")) #Age-Length-Weight Relationships (INAPESCA 2020)
dat_p <- read.csv(here("data","andrew","dat_p.csv")) #Price-quantity data (OG Paper)
dat_pars <- read.csv(here("data","andrew","dat_pars.csv")) %>% mutate(across(4:6, round, 6)) #Overall parameters (OG Paper)

```

```{r growth parameters}

# Define the parameters for the biological resource
r <- 0.23 #intrinsic rate of population increase ** (Needed: Ere)
k <- 20226 #carrying capacity (biomass in t) (source: INAPESCA)
theta <- 0.0005526788 #catchability (needs to be effort per tonne of biomass) (source: INAPESCA via Andrew)

```


```{r poaching effort}

# Define the parameters for the poaching effort
# Fixed parameters
n <- 0.1
theta <- 2 #cost parameter, assumed to be 2 (fixed)
z <- 2 * W 

# Estimated parameters, poaching
P <- 624310.9 # exogenous market price per unit of output ($USD per tonne of totoaba biomass, assuming each totoaba is 25.7 kg and has a 500 g buche)
W <-  3588.436 # poaching cost parameter, increases proportionally with effort (operational annual cost only, $USD per tonne of totoaba biomass)
c <- 1208.372 #cost of trading, all the costs associated with the transportation and final sale of wild animal products (assumed to be annual probability of gear or vessel confiscation, or arrest)
s <- 34594.88 # price paid to poachers ($USD per tonne of totoaba biomass, assuming each totoaba is 25.7 kg and has a 500 g buche)

# Estimated parameters, farming
v <- 8828.34 # farming cost parameter ($USD per tonne of totoaba biomass)
lambda <- 0.75 #gamma

alpha <- 2956477 #inverse demand parameter
beta <- 333065 #inverse demand parameter
  
initial_x <- 1400 #t of totoaba in 2017
initial_E <- 2.878333 # Catch-per-unit-effort, Totoaba (tonnes) per Vessel per Year (Median value is 0.4), considering the fishery is active for six months of the year

```

```{r calculating P and s}

P_par <- read.csv(here("data","P_par.csv")) # Price in end-markets, from INAPESCA Fig 4.4
s_par <- read.csv(here("data","s_par.csv"))  # Price paid to fishers on beaches, from INAPESCA Fig 4.4

### Calculate s, price paid to poachers ($USD per tonne of totoaba biomass)

s_par <- s_par %>%
  mutate(toto_weight_kg=(weight_g_fresh/0.019455253)/1000) %>% 
  mutate(weight_kg_fresh=weight_g_fresh/1000) %>% 
  mutate(toto_weight_t=toto_weight_kg/1000) %>% 
  mutate(number_of_toto=1/toto_weight_t) %>% 
  mutate(price_per_t=number_of_toto*(price_usd_perkg))

# Therefore, we convert swim bladder weight to totoaba weight assuming that the swim bladder makes up 1.95% of adult weight

# To calculate a single value for 's' we assume each totoaba is an average weight of 25.7 kg (and has a 500 gram buche) (this is reflected by averages reported by INAPESCA 2020)

# We multiple number of individuals that make up one tonne x price per tonne USD = to get $USD/tonne totoaba

# Lastly, we estimate the average price paid to poachers for the average swim bladder (a 500 gram swim bladder)

# 38.91051 individual totoaba per tonne (of size 25.7 kg, producing a 500 gram swim bladder) x $889.1 USD/kilogram = $34,594.88 USD/tonne of totoaba

lm <- lm(price_usd_perkg~weight_kg_fresh, data=s_par)
summary(lm)

ggplot(aes(y=price_usd_perkg, x=weight_kg_fresh), data=s_par) +
  geom_point()



### Now calculating P, exogenous market price per unit of output ($USD per tonne of totoaba biomass)

# We assume each totoaba is an average weight of 25.7 kg (and has a 500 gram buche) (this is reflected by averages reported by INAPESCA 2020)

# Therefore, there are 38.91 individual totoaba in a tonne.

# Each average individual (assuming each individual has a 500 gram buche) is worth $16,045 USD

# Therefore, 38.91 individuals x $16,045 USD = $624,310.9 USD/tonne of totoaba



# Estimating price premium for Ere

lm_P_par_kg <- lm(price_per_kg_dried ~ weight_kg_dried, data=P_par)
summary(lm_P_par_kg)

```

```{r calculating effort}

# Effort measured in number of vessels
# Therefore, CPUE is Totoabas/Vessels, or tonnes of Totoaba/Vessel

# Calculating initial Aggregate Poaching Effort, E
E_par <- read.csv(here("data","E_par.csv")) # Effort breakdown, from INAPESCA Fig 4.2
w_par <- read.csv(here("data","w_par.csv")) # Cost data, from Buche Bros

E_par <- E_par %>% 
  mutate(days_permonth = (days_perweek*weeks_permonth)) %>% 
  mutate(sets_permonth = (days_permonth*sets_pervessel_day)) %>% 
  mutate(sets_vessels_permonth = vessels*sets_permonth) %>% 
  mutate(totoaba_per_vessel = totoabas_year/vessels) %>% 
  mutate_at(vars(totoaba_per_vessel), ~replace(., is.nan(.), 0)) %>% 
  mutate(totoaba_t_per_vessel = biomass_captured_t/vessels) %>% 
  mutate_at(vars(totoaba_t_per_vessel), ~replace(., is.nan(.), 0))

E_val <- E_par %>% 
  summarize(median=median(totoaba_t_per_vessel),
            mean=mean(totoaba_t_per_vessel))

# W parameter, proportional increase in cost per unit of effort
# x axis should be effort (number of vessels)
# y axis should be cost per vessel

#Step one, get all annual operating costs

# Goal is to calculate cost per vessel trip (we have total fleet days per year which is number of vessels * fishing days per month)

# First calculate total annual costs for the entire fleet

w_par_ops <- w_par %>% 
  mutate(cost_crew_earnings = (totoaba_year * price_fishers_per_totoaba * monthly_earnings_paid)) %>% 
  mutate(cost_food_fuel = (foodfuel_day * total_fleet_days_year)) %>% 
  mutate(cost_gear = total_fleet_days_year*(gear_loss_day*gear_replacement)) %>% 
  mutate(revenue_per_month = (totoaba_year*(price_fishers_per_totoaba)) - (cost_crew_earnings-cost_food_fuel-cost_gear))

# Next, divide by total fishing days per year

w_par_val <- w_par_ops %>% 
  select(vessels, totoaba_day, total_fleet_days_year,cost_crew_earnings,cost_food_fuel,cost_gear,revenue_per_month) %>% 
  mutate(cost_per_trip = (cost_crew_earnings + cost_food_fuel + cost_gear)/total_fleet_days_year) %>% 
  mutate(cost_per_totoaba_per_trip = cost_per_trip/totoaba_day) %>% 
  mutate(revenue_per_trip=revenue_per_month/total_fleet_days_year) %>% 
  mutate(diff=revenue_per_trip-cost_per_trip)

# Calculate mean values

w_par_av <- w_par_val %>% 
  #filter(vessels > 1) %>% 
  mutate_at(vars(cost_per_trip), ~replace(., is.nan(.), 0)) %>% 
  mutate_at(vars(cost_per_totoaba_per_trip), ~replace(., is.nan(.), 0)) %>% 
  summarize(av_cost_per_trip=mean(cost_per_trip),
         av_cost_per_totoaba_per_trip=mean(cost_per_totoaba_per_trip))

# Step two, add in probability of enforcement action (i.e. fines, gear, or vessel confiscation)
# Treating step two as a calculation of c, cost of trading

# cost to cartels

c_par_val <- w_par_ops %>% 
  mutate(running_cost_c=((prob_fine*fine) +(prob_gear_conf*gear_conf)+(prob_vessel_conf*vessel_cost)))


```

```{r farming costs}

v_par <- read.csv(here("data","v_par.csv")) # Farming cost data, from Buche Bros
aqua_par_w <- read.csv(here("data","aqua_par_wild.csv"))
aqua_par_f <- read.csv(here("data","aqua_par_farm.csv"))

v_par <- v_par %>% 
  mutate(operating_costs = (maintenance_year+cleaning_year+vessel_maintenance_year+fuel_year+feed+labor+facility_lease+admin)) %>% 
  mutate(operating_costs/capacity_per_sphere_t)

```

```{r demand curve}

# p is price per gram for end-market prices in 2019 USD
# q is metric tonnes of dried buche from the fishery

# Step 1. Convert price per gram to price per tonne

dat_p <- dat_p %>% 
  mutate(price_per_buche_grams=p*g) 

# Fine tuning this by calculating the totoaba size that produces each buche size:

dat_p <- dat_p %>%
  mutate(toto_weight_kg=(g/0.019455253)/1000) %>% 
  mutate(toto_weight_t=toto_weight_kg/1000) %>% 
  mutate(number_of_toto=1/toto_weight_t)

# Therefore, 

dat_p <- dat_p %>%
  mutate(individuals_shipment = q*number_of_toto)

# Total shipment value is price * number of size-converted individuals

dat_p <- dat_p %>%
  mutate(shipment_value = individuals_shipment*price_per_buche_grams)

# Calculating new inverse demand

lm <- lm(shipment_value~q, data=dat_p)
summary(lm)

# new alpha 2956477
# new beta 333065

```
